"""AtlasPower-4S netlist, built from design.py so the numbers cannot drift.

Every part carries its footprint and, where one was verified, its LCSC part number. The
`build()` function returns (components, nets) and is the single source the schematic, the
PCB and the BOM are all generated from.

Circuit, front to back:

  XT90 -> fuse -> TVS -> ideal-diode FET (reverse polarity) -> shunt -> VIN bus
  VIN -> three independent AP64501 synchronous bucks -> 10 V, 7.4 V, 5 V
  INA226 across the shunt reports pack voltage and total current over I2C

The ideal diode matters more than it looks: an XT90 can be plugged in backwards, and a 4S
pack into a reversed input destroys every regulator at once. A series Schottky would cost
0.4 V and 3 W; the LM74700 regulates the FET to a 20 mV drop instead.
"""
import design as D

AP = 'AP64501SP-13'
FP_SO8EP = 'Package_SO:SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.29x3mm'
FP_0805 = 'Resistor_SMD:R_0805_2012Metric'
FP_C0805 = 'Capacitor_SMD:C_0805_2012Metric'
FP_C1210 = 'Capacitor_SMD:C_1210_3225Metric'
FP_2512 = 'Resistor_SMD:R_2512_6332Metric'
# Generated by gen_footprint.py from the Bourns SRP1265A datasheet Recommended Layout
# (14.2 mm span, 8.0 mm gap, 5.0 mm pad height, giving 3.1 mm pads at +-5.55). KiCad ships
# no SRP1265A land pattern; this one is built from the drawing and its geometry is checked.
FP_IND = 'atlaspower:L_Bourns_SRP1265A'
FP_ELEC = 'Capacitor_SMD:CP_Elec_10x10.5'


class Part:
    def __init__(self, ref, value, footprint, pins, lcsc='', mpn='', desc=''):
        self.ref, self.value, self.footprint = ref, value, footprint
        self.pins = pins                 # {pin number (str): net name}
        self.lcsc, self.mpn, self.desc = lcsc, mpn, desc

    def __repr__(self):
        return f'<{self.ref} {self.value}>'


def build():
    P = []
    add = P.append

    # ---- input protection -------------------------------------------------------------
    add(Part('J1', 'XT90 / 4S LiPo in', 'TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-3-2-5.08_1x02_P5.08mm_Horizontal',
             {'1': 'VBAT_RAW', '2': 'GND'}, desc='pack input, 24 A rated block'))
    add(Part('F1', '10A blade', 'Fuse:Fuse_Blade_ATO_directSolder',
             {'1': 'VBAT_RAW', '2': 'VBAT'}, desc='ATO blade, the one user-serviceable fuse'))
    add(Part('D1', 'SMBJ22A', 'Diode_SMD:D_SMB',
             {'1': 'GND', '2': 'VBAT'}, lcsc='C13964', desc='TVS, 22 V standoff, clamps motor regen'))
    # LM74700 ideal diode controller: 1 VCAP, 2 GND, 3 EN, 4 CATHODE, 5 GATE, 6 ANODE
    add(Part('U1', 'LM74700QDBVRQ1', 'Package_TO_SOT_SMD:SOT-23-6',
             {'1': 'IDEAL_CAP', '2': 'GND', '3': 'IDEAL_EN', '4': 'VIN_PRE', '5': 'IDEAL_GATE', '6': 'VBAT'},
             lcsc='C2941042', mpn='LM74700QDBVRQ1', desc='ideal diode controller, reverse battery'))
    add(Part('Q1', 'ASS053N06Q1M-R', 'Package_SO:PowerPAK_SO-8_Single',
             {'1': 'IDEAL_GATE', '2': 'VIN_PRE', '3': 'VIN_PRE', '4': 'VIN_PRE', '5': 'VBAT',
              '6': 'VBAT', '7': 'VBAT', '8': 'VBAT'},
             lcsc='C53896939', mpn='ASS053N06Q1M-R', desc='60 V 5.5 mohm N-FET, source to pack, drain to load'))
    add(Part('C1', '100n/50V', FP_C0805, {'1': 'IDEAL_CAP', '2': 'VBAT'}, desc='LM74700 charge-pump cap'))
    add(Part('C2', '100n/50V', FP_C0805, {'1': 'VIN_PRE', '2': 'GND'}, desc='LM74700 cathode bypass'))
    add(Part('R1', '100k', FP_0805, {'1': 'VBAT', '2': 'IDEAL_EN'}, desc='ideal-diode enable pull-up'))
    add(Part('J2', 'E-STOP', 'Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical',
             {'1': 'IDEAL_EN', '2': 'GND'}, desc='short to kill every rail; leave open to run'))

    # ---- current sense ----------------------------------------------------------------
    add(Part('R2', '5m/2W', FP_2512, {'1': 'VIN_PRE', '2': 'VIN'},
             lcsc='C2962780', desc='INA226 shunt, 40 mV at 8 A'))
    # INA226 MSOP-10: 1 IN+, 2 IN-, 3 ALERT, 4 GND, 5 -, 6 SCL, 7 SDA, 8 -, 9 VS, 10 A0/A1
    add(Part('U2', 'INA226AIDGSR', 'Package_SO:MSOP-10-1EP_3x3mm_P0.5mm_EP1.68x1.88mm',
             {'1': 'VIN_PRE', '2': 'VIN', '3': 'ALERT', '4': 'GND', '5': 'GND',
              '6': 'SCL', '7': 'SDA', '8': 'GND', '9': 'V3V3_EXT', '10': 'GND',
              '11': 'GND'},   # exposed pad; unmapped it floated and DRC called it out
             lcsc='C49851', mpn='INA226AIDGSR', desc='pack voltage + current telemetry'))
    add(Part('C3', '100n/16V', FP_C0805, {'1': 'V3V3_EXT', '2': 'GND'}, desc='INA226 supply bypass'))
    add(Part('R3', '4k7', FP_0805, {'1': 'SDA', '2': 'V3V3_EXT'}, desc='I2C pull-up'))
    add(Part('R4', '4k7', FP_0805, {'1': 'SCL', '2': 'V3V3_EXT'}, desc='I2C pull-up'))
    add(Part('J3', 'I2C / Qwiic', 'Connector_JST:JST_SH_SM04B-SRSS-TB_1x04-1MP_P1.00mm_Horizontal',
             {'1': 'GND', '2': 'V3V3_EXT', '3': 'SDA', '4': 'SCL'},
             desc='to the Jetson 40-pin header: 3.3 V, SDA, SCL, GND'))

    # ---- three identical buck rails ---------------------------------------------------
    # refdes blocks: rail A (10 V) 1xx, rail B (7.4 V) 2xx, rail C (5 V) 3xx
    for idx, (net, vout, ic, ip, _) in enumerate(D.RAILS):
        n = idx + 1
        p = f'{n}0'
        sw, bst, fb, comp, ss, en = f'SW{n}', f'BST{n}', f'FB{n}', f'COMP{n}', f'SS{n}', f'EN{n}'
        rtop = D.fb_top(vout)
        r5, c5, c6 = D.compensation(vout, ic)
        add(Part(f'U{n+2}', AP, FP_SO8EP,
                 {'1': bst, '2': 'VIN', '3': en, '4': ss, '5': fb, '6': comp, '7': 'GND', '8': sw, '9': 'GND'},
                 lcsc='C2071517', mpn=AP, desc=f'synchronous buck, {vout} V at {ic} A'))
        add(Part(f'L{n}', '10uH/15.5A', FP_IND, {'1': sw, '2': net},
                 lcsc='C840531', mpn='SRP1265A-100M', desc='shielded power inductor'))
        add(Part(f'C{p}1', '100n/50V', FP_C0805, {'1': bst, '2': sw}, desc='bootstrap, datasheet 100 nF'))
        for k in (2, 3):                                   # input ceramics, close to VIN/GND
            add(Part(f'C{p}{k}', '10u/50V', FP_C1210, {'1': 'VIN', '2': 'GND'}, desc='input ceramic'))
        for k in (4, 5, 6):                                # output ceramics, datasheet 3 x 22 uF
            add(Part(f'C{p}{k}', '22u/25V', FP_C1210, {'1': net, '2': 'GND'}, desc='output ceramic'))
        add(Part(f'C{p}7', f'{c5:.1f}n', FP_C0805, {'1': comp, '2': 'GND'}, desc='loop zero, Eq. 18'))
        add(Part(f'C{p}8', f'{c6:.0f}p', FP_C0805, {'1': comp, '2': 'GND'}, desc='loop pole, Eq. 19'))
        add(Part(f'C{p}9', '10n/25V', FP_C0805, {'1': ss, '2': 'GND'}, desc='soft start, 4 ms'))
        add(Part(f'R{p}1', f'{rtop:.0f}k', FP_0805, {'1': net, '2': fb}, desc='feedback top'))
        add(Part(f'R{p}2', '22k1', FP_0805, {'1': fb, '2': 'GND'}, desc='feedback bottom'))
        add(Part(f'R{p}3', f'{r5:.1f}k', FP_0805, {'1': comp, '2': f'COMPZ{n}'}, desc='loop resistor, Eq. 17'))
        add(Part(f'C{p}10', '2u2/16V', FP_C0805, {'1': f'COMPZ{n}', '2': 'GND'}, desc='loop series cap'))
        add(Part(f'R{p}4', '100k', FP_0805, {'1': 'VIN', '2': en}, desc='enable pull-up to VIN'))
        add(Part(f'C{p}11', '10n/50V', FP_C0805, {'1': en, '2': 'GND'}, desc='stagger start, ~8 ms apart'))
        add(Part(f'D{n+1}', 'green', 'LED_SMD:LED_0805_2012Metric', {'2': net, '1': f'LED{n}'},
                 desc='rail present'))
        add(Part(f'R{p}5', '4k7', FP_0805, {'1': f'LED{n}', '2': 'GND'}, desc='LED series'))

    # bulk electrolytics: input, and the servo rail which sees stall transients
    add(Part('C41', '220u/35V', FP_ELEC, {'1': 'VIN', '2': 'GND'}, desc='input bulk'))
    add(Part('C42', '470u/16V', FP_ELEC, {'1': 'VOUT_7V4', '2': 'GND'}, desc='servo stall reservoir'))

    # ---- outputs ----------------------------------------------------------------------
    add(Part('J4', 'Jetson 10V', 'Connector_BarrelJack:BarrelJack_Horizontal',
             {'1': 'VOUT_10V', '2': 'GND', '3': 'GND'}, desc='5.5 x 2.5 mm centre positive'))
    add(Part('F2', '1A T', 'Fuse:Fuseholder_Clip-5x20mm_Keystone_3512P_Inline_P23.62x7.27mm_D1.02x2.41x1.02x1.57mm_Horizontal',
             {'1': 'VOUT_10V', '2': 'LIDAR_V'}, desc='SICK requires an external slow-blow on the lidar'))
    add(Part('J5', 'TiM561 10V', 'TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-1,5-2-5.08_1x02_P5.08mm_Horizontal',
             {'1': 'LIDAR_V', '2': 'GND'}, desc='M12 brown = pin 1 +V, blue = pin 3 0 V'))
    add(Part('J6', 'servo 7.4V', 'Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical',
             {'1': 'GND', '2': 'VOUT_7V4', '3': 'SERVO_SIG'},
             desc='V+ and GND from this board; signal passes through from the VESC PPM header'))
    add(Part('J7', 'PPM in', 'Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical',
             {'1': 'GND', '2': 'NC_VESC_5V', '3': 'SERVO_SIG'},
             desc='from the VESC. Pin 2 is deliberately a dead net: the VESC 5 V must not '
                  'meet the BEC rail, which is the mistake this connector exists to prevent'))
    add(Part('J8', '5V out', 'TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-1,5-2-5.08_1x02_P5.08mm_Horizontal',
             {'1': 'VOUT_5V', '2': 'GND'}, desc='USB hub / PCA9685 / fan'))
    add(Part('H1', 'M3', 'MountingHole:MountingHole_3.2mm_M3', {}))
    add(Part('H2', 'M3', 'MountingHole:MountingHole_3.2mm_M3', {}))
    add(Part('H3', 'M3', 'MountingHole:MountingHole_3.2mm_M3', {}))
    add(Part('H4', 'M3', 'MountingHole:MountingHole_3.2mm_M3', {}))

    nets = {}
    for part in P:
        for pin, net in part.pins.items():
            nets.setdefault(net, []).append((part.ref, pin))
    return P, nets


def report():
    P, nets = build()
    lines = [f'{len(P)} parts, {len(nets)} nets']
    single = {n: c for n, c in nets.items() if len(c) < 2}
    lines.append(f'single-pin nets (each must be deliberate): {sorted(single)}')
    for n in sorted(nets):
        lines.append(f'  {n:12s} {len(nets[n]):2d}  ' + ' '.join(f'{r}.{p}' for r, p in nets[n]))
    return P, nets, '\n'.join(lines)


if __name__ == '__main__':
    P, nets, text = report()
    print(text)
